---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: heading
    label: Integrations
  - type: document
    path: forestry/integrations/newsletter-service.json
    label: Newsletter Service
    match: "**/*"
    read_only: false
  - type: heading
    label: One-off Pages
  - type: document
    path: forestry/pages/home.json
    label: Home
    match: "**/*"
  - type: document
    path: forestry/pages/about-me.json
    label: About Me
    match: "**/*"
  - type: heading
    label: Collections
  - type: directory
    path: forestry/collections/books
    label: Books
    create: documents
    match: "*.json"
    new_doc_ext: json
  - type: directory
    path: forestry/collections/series
    label: Series
    create: documents
    match: "*.json"
    new_doc_ext: json
  - type: directory
    path: forestry/collections/universes
    label: Universes
    create: documents
    match: "*.json"
    new_doc_ext: json
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
