---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
  - type: heading
    label: Integrations
  - type: document
    path: forestry/integrations/newsletter-service.json
    label: Newsletter Service
  - type: document
    path: forestry/integrations/affiliate-codes-service.json
    label: Affiliate Codes Service
  - type: heading
    label: One-off Pages
  - type: document
    path: forestry/pages/home.json
    label: Home
  - type: document
    path: forestry/pages/about-me.json
    label: About Me
  - type: heading
    label: Collections
  - type: directory
    path: forestry/collections/books
    label: Books
    create: documents
    match: "*.json"
    new_doc_ext: json
    templates:
      - book
  - type: directory
    path: forestry/collections/series
    label: Series
    create: documents
    match: "*.json"
    new_doc_ext: json
    templates:
      - series
  - type: directory
    path: forestry/collections/universes
    label: Universes
    create: documents
    match: "*.json"
    new_doc_ext: json
    templates:
      - universe
upload_dir: public/forestry
public_path: "/forestry"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry-preview
